stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-slim
    script: 
        - echo "Building"
        - pip3 install --upgrade pip
        - pip3 install -r requirements.txt
        - python3 predict.py
        - python3 rating_calc.py

test:
    stage: test
    image: python:3.8-slim
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - pip3 install nba_api
        - pip3 install -r requirements.txt

        # Run Test Cases
        # - python3 -m unittest pyunittest.py

        # Run Coverage
        - pip3 install coverage
        - coverage run pyunittest.py 
        - coverage report
        - coverage html -d coverage_reports

    artifacts:
        paths:
            - coverage_reports/
